// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfffmtuhpmsiqfnzjdqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZmZtdHVocG1zaXFmbnpqZHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTIwNjMsImV4cCI6MjA2ODgyODA2M30.30kl9pS4inWWJRDwVcBXigLnfHR1U-VC89NsxI6MiAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});